# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Template
version:      0.01
version_from: lib/Geo/Template.pm
installdirs:  site
requires:
    Geo::Constants:                0.04
    Geo::Ellipsoids:               0.09
    Geo::Functions:                0.03
    strict:                        0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
